//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// NotchingGradeInsp.rc에서 사용되고 있습니다.
//
#define IDCANCEL2                       3
#define IDOK2                           3
#define DC_BUT_RECIPEDELETE             3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_RESULT_VIEW                 101
#define IDS_INSP_INFO_VIEW              102
#define IDS_LOT_RESULT_VIEW             103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_NotchingGradeInspTYPE       130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_DLG_MODE                    310
#define IDB_LGES_LOGO                   313
#define IDB_RADIO_OFF32                 314
#define ID_VIEW_RESULT                  314
#define IDB_RADIO_ON32                  315
#define IDB_RADIO_ON                    316
#define IDB_RADIO_OFF                   317
#define IDB_APP_CLOSE                   319
#define IDD_DLG_INSP                    320
#define IDB_INSP_RUN                    325
#define IDB_INSP_PAUSE                  326
#define IDB_INSP_STOP                   327
#define IDD_DLG_HISTORY                 328
#define IDD_DLG_COND                    331
#define IDD_DISP_IMAGE_DLG              333
#define IDD_DLG_INSP_INFO               335
#define IDD_DLG_RESULT                  339
#define IDD_DLG_INSP_SIM                343
#define IDD_DLG_GRAPH                   345
#define IDD_DLG_RECIPE_SETTING          347
#define IDD_DLG_DIO_TEST                351
#define IDD_DLG_LIGHT_CTRL              353
#define IDD_DLG_CAMERA_SETTING          355
#define IDD_DLG_CAM_VIEW                357
#define IDD_DLG_HISTOGRAM               359
#define IDD_DLG_CAM_WAVE                361
#define IDD_DEBUG_IMG_ACQ_DLG           363
#define IDD_DLG_SYSTEM_SETTING          367
#define IDD_DLG_RECIPE_SELECT           369
#define IDD_DLG_DEBUG_SET               371
#define IDD_DLG_START                   373
#define IDB_BMPREMINDER                 375
#define IDD_DLG_DELETE_SETTING          376
#define IDD_DLG_USER_CHANGE             378
#define IDD_DLG_IMAGE_VIEWER            380
#define IDD_DLG_EXCEL_SAVE              382
#define IDD_DLG_DIRECTORY               384
#define IDD_DLG_ATTACH_IMAGE            386
#define IDD_DLG_CROP_IMAGE_VIEW         388
#define IDB_INSP_RUN_S                  390
#define IDB_INSP_STOP_S                 391
#define IDD_DLG_DEBUG_CTRL              392
#define IDD_DLG_HISTORY_LOT             394
#define IDD_DLG_DISPERROR               396
#define IDD_DLG_IO_MONITOR              398
#define IDB_GREEN_LED_ON                401
#define IDB_GREEN_LED_OFF               402
#define IDD_DEFECT_MAP_DLG              403
#define IDD_DLG_TACT_TIME_GRAPH         405
#define IDD_DLG_DISP_IMAGE              407
#define IDB_ULTIUMCELLS_LOGO            412
#define IDB_HLI_LOGO                    413
#define IDD_DLG_INITSYSTEMSETTING       414
#define IDD_LOGDISPLAYDLG               416
#define IDD_DLG_RECIPEIMPORT            418
#define IDC_BTN_LOG                     1000
#define IDC_COMBO                       1000
#define IDC_CHECK_HIGH_00               1001
#define IDC_BTN_EXIT                    1002
#define IDC_CHECK_HIGH_01               1002
#define IDC_RADI_INSP_MODE              1003
#define IDC_CHECK_HIGH_02               1003
#define IDC_RAD_HISTORY_MODE            1004
#define IDC_CHECK_HIGH_03               1004
#define IDC_RAD_COND_MODE               1005
#define IDC_CHECK_HIGH_04               1005
#define IDC_CHECK_HIGH_05               1006
#define IDC_CHECK_HIGH_06               1007
#define IDC_ED_STATE                    1008
#define IDC_CHECK_HIGH_07               1008
#define IDC_ED_TITLE                    1009
#define IDC_CHECK_HIGH_08               1009
#define IDC_CHECK_HIGH_09               1010
#define IDC_CHECK_HIGH_10               1011
#define IDC_CHECK_HIGH_11               1012
#define IDC_CHECK_HIGH_12               1013
#define IDC_RAD_CAM_01                  1013
#define IDC_RAD_ANODE_MODE              1013
#define IDC_RD_MONTH                    1013
#define IDC_RAD_RUN                     1013
#define IDC_CHECK_HIGH_13               1014
#define IDC_RAD_CAM_02                  1014
#define IDC_RAD_CATHODE_MODE            1014
#define IDC_RD_NG_CROP                  1014
#define IDC_RAD_STOP                    1014
#define IDC_RAD_BRIGHT_ROLL             1014
#define IDC_CHECK_HIGH_14               1015
#define IDC_RD_NG                       1015
#define IDC_RAD_KOREAN                  1015
#define IDC_RAD_ENGLISH                 1016
#define IDC_CHECK_HIGH_15               1016
#define IDC_RD_OK_CROP                  1016
#define IDC_BTN_ZOOM_IN                 1017
#define IDC_RD_OK                       1017
#define IDC_BTN_ZOOM_OUT                1019
#define IDC_ED_RATE                     1020
#define IDC_LIST_CLEAR                  1020
#define IDC_ED_DISPMEASRSLT             1021
#define IDC_STATIC_HIGH                 1021
#define IDC_ST_DISP_POS                 1022
#define IDC_STATIC_LOW                  1022
#define IDC_ST_IMAGE_BTM                1023
#define IDC_CHECK_INTRRUPT              1023
#define IDC_ST_IMAGE_TAB                1024
#define IDC_CHECK_RISING                1024
#define IDC_ST_DEBUG_STATUS             1025
#define IDC_CHECK_LOW_00                1025
#define IDC_ST_LOGO                     1026
#define IDC_CHECK_LOW_01                1026
#define IDC_CHECK_LOW_02                1027
#define IDC_CHECK_LOW_03                1028
#define IDC_BTN_IMAGE_ACQ_START         1028
#define IDC_BTN_CAM_PARAM_SET_ALL       1028
#define IDC_BTN_DEBUG_SETTING           1028
#define IDC_BTN_LOT_CHANGE              1028
#define IDC_BTN_PREV                    1028
#define IDC_BTN_SET_PATH                1028
#define IDC_BTN_DIRECTORY               1028
#define IDC_BTN_CSV_OPEN                1028
#define IDC_BTN_CROP_SAVE               1028
#define IDC_BTN_LOAD_IMG_1              1028
#define IDC_BTN_DUMMY_ERROR             1028
#define IDC_BTN_DISP_IMAGE              1028
#define IDC_BUT_EQP_SETTING             1028
#define IDC_CHECK_LOW_04                1029
#define IDC_BTN_TODAY                   1029
#define IDC_BTN_LOAD_IMG_2              1029
#define IDC_BUT_CAMERA_SETTING          1029
#define IDC_BTN_DUMMY_ERROR2            1029
#define IDC_BTN_DUMMY_ERROR_CLEAR       1029
#define IDC_ST_GRUP_RECIPE              1030
#define IDC_CHECK_LOW_05                1030
#define IDC_BTN_NEXT                    1030
#define IDC_BUT_RESULT_DELETE           1030
#define IDC_ST_GRUP_WORK                1031
#define IDC_CHECK_LOW_06                1031
#define IDC_RD_WEEK                     1031
#define IDC_BUT_DISPLAY_SETTING         1031
#define IDC_ST_GRUP_LIGHT               1032
#define IDC_CHECK_LOW_07                1032
#define IDC_BUT_OTHER_SETTING           1032
#define IDC_EDIT1                       1033
#define IDC_ED_TAB_PITCH_MM             1033
#define IDC_CHECK_LOW_08                1033
#define IDC_ED_REF_LIGHT_01             1033
#define IDC_ED_SPEED                    1033
#define IDC_ED_IMAGE_FILE_NAME          1033
#define IDC_ED_IMAGE_COUNT              1033
#define IDC_ED_EDGE_DET_MEAN_WIDTH      1033
#define IDC_ED_RECIPE_NAME              1033
#define IDC_ED_BACKUP_DIRECTORY         1033
#define IDC_ED_PASSWORD                 1033
#define IDC_ED_SERCH_LOTID              1033
#define IDC_ED_SAVE_PATH                1033
#define IDC_ED_CSV_PATH                 1033
#define IDC_ED_IMAGE_1                  1033
#define IDC_ED_ALARM_OUT                1033
#define IDC_EDIT_MACHINE_MODE           1033
#define IDC_EDIT2                       1034
#define IDC_ED_TAB_WIDTH_MM             1034
#define IDC_CHECK_LOW_09                1034
#define IDC_ED_REF_LIGHT_02             1034
#define IDC_ED_EXPOSURE_TIME            1034
#define IDC_ED_SEL_DIR                  1034
#define IDC_ED_RESOLUTION_VER           1034
#define IDC_ED_NEXT_RECIPE_NAME         1034
#define IDC_ED_BACKUP_DAY               1034
#define IDC_ED_PASSWORD2                1034
#define IDC_ED_NG_IMAGE_PATH            1034
#define IDC_ED_IMAGE_2                  1034
#define IDC_ED_MSGSTR                   1034
#define IDC_ED_ALARM_BIT                1034
#define IDC_BUT_ADDRESS_SETTING         1034
#define IDC_EDIT3                       1035
#define IDC_ED_TAB_RADIUS_MM            1035
#define IDC_CHECK_LOW_10                1035
#define IDC_ED_DIFF_REF_LIGHT_01        1035
#define IDC_ED_GAIN                     1035
#define IDC_ED_LOT_ID                   1035
#define IDC_ED_MACHINE_ID               1035
#define IDC_ED_DUMMY_D                  1035
#define IDC_BTN_USER_CHANGE             1035
#define IDC_ED_OK_IMAGE_PATH            1035
#define IDC_EDIT_EDGE_DET_MEAN_WIDTH    1035
#define IDC_ED_TOP_COAT_HEIGHT_MM       1036
#define IDC_CHECK_LOW_11                1036
#define IDC_ED_DIFF_REF_LIGHT_02        1036
#define IDC_ED_DELETE_DAY               1036
#define IDC_ST_USER_MODE                1036
#define IDC_ED_BIT_IN_ADDRESS           1036
#define IDC_EDIT_RESOLUTION_HOR_CAM_NO_00 1036
#define IDC_ED_BTM_COAT_HEIGHT_MM       1037
#define IDC_CHECK_LOW_12                1037
#define IDC_ED_DUMMY                    1037
#define IDC_ED_START_TIME               1037
#define IDC_EDIT_RESOLUTION_HOR_CAM_NO_01 1037
#define IDC_ED_TAB_COAT_HEIGHT_MM       1038
#define IDC_CHECK_LOW_13                1038
#define IDC_CMB_RECIPE_SELECT           1038
#define IDC_COM_RECIPE_SELECT           1038
#define IDC_CMB_TIME_START              1038
#define IDC_CMB_MAP_DISP_LENGTH         1038
#define IDC_ED_BIT_OUT_ADDRESS          1038
#define IDC_EDIT_RESOLUTION_VER         1038
#define IDC_COMBO_RECIPE_NAME           1038
#define IDC_COMBO_SPECIALLOGNAME        1038
#define IDC_ED_COAT_BRIGHT              1039
#define IDC_CHECK_LOW_14                1039
#define IDC_ED_JPEG_SAVE_QUALITY        1039
#define IDC_ED_END_TIME                 1039
#define IDC_CMB_TIME_END                1039
#define IDC_EDIT_MACHINE_ID             1039
#define IDC_ED_ROLL_BRIGHT              1040
#define IDC_CHECK_LOW_15                1040
#define IDC_ED_WORD_IN_ADDRESS          1040
#define IDC_ST_STATE                    1041
#define IDC_ED_TAB_PITCH_PIX            1041
#define IDC_ED_WORD_OUT_ADDRESS         1041
#define IDC_EDIT_GRAPH_SIZE_FOILEXP     1041
#define IDC_ED_TAB_WIDTH_PIX            1042
#define IDC_BUTTON_EXIT                 1042
#define IDC_ST_CAMERA_STATE             1042
#define IDC_ED_RESULT_SAVE_PERIOD       1042
#define IDC_EDIT_GRAPH_SIZE_SURFACE     1042
#define IDC_ST_TITLE                    1043
#define IDC_ED_TAB_RADIUS_PIX           1043
#define IDC_CHECK_FALLING               1043
#define IDC_ED_DISK_CAPACITY_ALARM      1043
#define IDC_EDIT_DISPLAY_LANGUAGE       1043
#define IDC_CHK_REFRESH                 1044
#define IDC_ED_TOP_COAT_HEIGHT_PIX      1044
#define IDC_LIST_Message                1044
#define IDC_ED_IP                       1044
#define IDC_EDIT_LOGO                   1044
#define IDC_ST_LOT_ID                   1045
#define IDC_ED_TAB_COAT_HEIGHT_PIX      1045
#define IDC_RADIO_MESSAGE               1045
#define IDC_ED_PORT                     1045
#define IDC_EDIT_PLC_MODE               1045
#define IDC_ED_BTM_COAT_HEIGHT_PIX      1046
#define IDC_RADIO_CALLBACK              1046
#define IDC_ED_BIT_IN_ADDRESS_16        1046
#define IDC_EDIT_PLC_IP_ADDRESS         1046
#define IDC_ST_NUM_TOTAL                1047
#define IDC_ED_FOIL_THRES_UPPER         1047
#define IDC_RADIO_EVENT                 1047
#define IDC_ST_PLC_STATE                1047
#define IDC_ED_BIT_OUT_ADDRESS_16       1047
#define IDC_EDIT_PLC_PORT               1047
#define IDC_ST_NUM_OK                   1048
#define IDC_ED_TAB_RADIUS_PIX_H         1048
#define IDC_ST_IO_STATE                 1048
#define IDC_ED_WORD_IN_ADDRESS_16       1048
#define IDC_EDIT_TRIGGER_MODE           1048
#define IDC_ST_NUM_NG                   1049
#define IDC_ST_LIGHT_STATE              1049
#define IDC_ED_WORD_OUT_ADDRESS_16      1049
#define IDC_EDIT_ACQISITION_RATE_CAM_NO_00 1049
#define IDC_ED_PET_MATRIX_X             1049
#define IDC_ST_DISK_SPACE               1050
#define IDC_ST_NUM_YIELD                1050
#define IDC_EDIT_ACQISITION_RATE_CAM_NO_01 1050
#define IDC_ED_JPEG_SAVE_QUALITY2       1050
#define IDC_ED_OVERFLOW_MAX             1050
#define IDC_ED_PET_THRESHOLD            1050
#define IDC_EDIT_GAIN_CAM_NO_00         1051
#define IDC_ED_PET_CHECK_CNT            1051
#define IDC_ED_MISS_TAB_ID_MAX          1051
#define IDC_EDIT_GAIN_CAM_NO_01         1052
#define IDC_EDIT_EXPOSURE_TIME_CAM_NO_00 1054
#define IDC_EDIT_EXPOSURE_TIME_CAM_NO_01 1055
#define IDC_EDIT_VIEW_OFFSET_HOR_CAM_NO_00 1056
#define IDC_EDIT_VIEW_OFFSET_HOR_CAM_NO_01 1057
#define IDC_EDIT_VIEW_WIDTH_CAM_NO      1058
#define IDC_EDIT_VIEW_HEIGHT_CAM_NO     1059
#define IDC_BTN_FILE_OPEN               1060
#define IDC_EDIT_CAMERA_IMAGE_FLIP_00   1060
#define IDC_BTN_PROC_ALL                1061
#define IDC_EDIT_CAMERA_IMAGE_FLIP_01   1061
#define IDC_BTN_IMG_ORG                 1062
#define IDC_EDIT_GRID_FONT_SIZE         1062
#define IDC_BTN_IMG_PROC1               1063
#define IDC_EDIT_ENABLE_MARKER          1063
#define IDC_BTN_IMG_PROC2               1064
#define IDC_EDIT_JPEG_SAVE_QUALITY      1064
#define IDC_BTN_IMG_PROC3               1065
#define IDC_EDIT_ENABLE_NG_STOP         1065
#define IDC_BTN_IMG_PROC4               1066
#define IDC_EDIT_ENABLE_MARKING_ALL_TAB 1066
#define IDC_BTN_IMG_PROC5               1067
#define IDC_EDIT_FIRST_TAB_DONOT_PROCESS 1067
#define IDC_BTN_IMG_PROC6               1068
#define IDC_EDIT_RESULT_SAVE_PERIOD     1068
#define IDC_BTN_IMG_PROC7               1069
#define IDC_EDIT_DISK_CAPACITY_ALARM    1069
#define IDC_ST_IMG_SEL_GROUP            1070
#define IDC_BTN_INSP_SIM                1071
#define IDC_EDIT_BIT_IN                 1071
#define IDC_ST_TAC_INFO                 1072
#define IDC_EDIT_BIT_OUT                1072
#define IDC_BTN_DETECT_LINE             1073
#define IDC_EDIT_WORD_IN                1073
#define IDC_CHK_DISP_LINE               1074
#define IDC_EDIT_WORD_OUT               1074
#define IDC_BTN_RECIPE_SET              1075
#define IDC_EDIT_SLAVE_ID               1075
#define IDC_GRID_CTRL_DEF               1076
#define IDC_BTN_DIVISION_TAB            1077
#define IDC_CHK_DEF_LINK                1078
#define IDC_GRAPH_CAM1                  1089
#define IDC_GRAPH_CAM2                  1090
#define IDC_GRAPH_CAM3                  1091
#define IDC_GRAPH_CAM4                  1092
#define IDC_CHK_CAM1_DATA1              1094
#define IDC_CHK_CAM1_DATA2              1095
#define IDC_ED_TEMP                     1095
#define IDC_CHK_CAM1_DATA3              1096
#define IDC_ED_FOIL_THRES_LOW           1096
#define IDC_CHK_CAM2_DATA1              1097
#define IDC_ED_DROSS_THRES_LOW          1097
#define IDC_CHK_CAM2_DATA2              1098
#define IDC_ED_MIN_SIZE_FOIL            1098
#define IDC_CHK_CAM2_DATA3              1099
#define IDC_ED_MIN_SIZE_DROSS           1099
#define IDC_CHK_CAM1_DATA_TOTAL         1100
#define IDC_ED_MASK_OFFSET_FOIL         1100
#define IDC_CHK_CAM2_DATA_TOTAL         1101
#define IDC_ED_MASK_OFFSET_DROSS        1101
#define IDC_ED_INSP_RANGE_IN            1102
#define IDC_ED_INSP_RANGE_OUT           1103
#define IDC_ED_DROSS_THRES_UPPER        1104
#define IDC_ED_PET_MATRIX_Y             1105
#define IDC_ST_RECIPE_NAME              1106
#define IDC_BTN_SAVE                    1107
#define IDC_BTN_TEST                    1108
#define IDC_ST_RECIPE_NAME2             1108
#define IDC_CHK_CAM1_INDIVIDUAL         1109
#define IDC_BTN_INSP_SPETER             1109
#define IDC_CHK_CAM2_INDIVIDUAL         1110
#define IDC_BTN_SET_ALL                 1113
#define IDC_ED_COAT_BRIGHT_HIGH         1114
#define IDC_ED_ROLL_BRIGHT_HIGH         1115
#define IDC_ST_LINK_RANGE_X             1116
#define IDC_BTN_SET_SPEED               1116
#define IDC_ST_LINK_RANGE_Y             1117
#define IDC_BTN_SET_EXPTIME             1117
#define IDC_FOIL_LINK_RANGE_X           1118
#define IDC_BTN_SET_GAIN                1118
#define IDC_DROSS_LINK_RANGE_X          1119
#define IDC_CHK_PRE_FILTER              1119
#define IDC_FOIL_LINK_RANGE_Y           1120
#define IDC_ST_RECIPE_GROUP             1120
#define IDC_DROSS_LINK_RANGE_Y          1121
#define IDC_GRID_CTRL_JUDGE             1122
#define IDC_GRID_RECIPE_SET             1122
#define IDC_GRID_CTRL_LIGHT             1123
#define IDC_BTN_START                   1123
#define IDC_GRID_CTRL_MARKING           1124
#define IDC_ST_CAM_01                   1126
#define IDC_ST_CAM_02                   1127
#define IDC_TAB_DETECT_COND             1128
#define IDC_CHK_FREERUN                 1129
#define IDC_CHK_DISP_DEFECT             1130
#define IDC_ED_BMP_SAVE_INTERVAL        1131
#define IDC_CHK_MEASURE                 1132
#define IDC_TAB_INFO                    1135
#define IDC_CUST_HISTOGRAM              1136
#define IDC_BTN_HISTOGRAM               1137
#define IDC_CHK_TRIGGER_MODE            1138
#define IDC_CHK_WAVE_RUN                1138
#define IDC_CHK_SAVE_ONLY_NG_TAB        1138
#define IDC_CHK_INFINIT                 1138
#define IDC_CHK_EXTERNAL_TRIGGER        1138
#define IDC_CHK_STOP_DURING_RUN         1138
#define IDC_CHK_PASSWORD_CHANGE         1138
#define IDC_CHK_SWITCH_DISP             1138
#define IDC_BTN_RESET_COUNT             1138
#define IDC_BTN_HISTOGRAM2              1138
#define IDC_CUST_CAM_WAVE               1139
#define IDC_CHK_TRG_MODE                1140
#define IDC_BTN_SELECT_FOLDER           1141
#define IDC_BTN_INITIALIZE              1142
#define IDC_BTN_IMAGE_ACQ_STOP          1143
#define IDC_PROGRESS1                   1144
#define IDC_CHK_DISABLE_PROC_DIFF       1145
#define IDC_ED_MAGNIFICATION            1146
#define IDC_CHK_ENABLE_DEF_LINK         1147
#define IDC_ED_NG_X_SIZE                1148
#define IDC_CALCTRL                     1148
#define IDC_ED_NG_Y_SIZE                1149
#define IDC_ST_HEADER                   1149
#define IDC_BTN_ONE_BY_ONE              1150
#define IDC_ED_NG_X_SIZE_BTM            1150
#define IDC_CHK_NG_STOP                 1151
#define IDC_CHK_ENABLE_MARKER           1151
#define IDC_CHK_NOTUSE_BACKUP           1151
#define IDC_CHK_ENABLE_NON_NG_SAVE      1152
#define IDC_CB_USERLIST                 1153
#define IDC_CHK_ENABLE_MARKER3          1153
#define IDC_CHK_ENABLE_NON_NG_STOP      1153
#define IDC_ST_USERMODE                 1154
#define IDC_ST_PASSWORD                 1155
#define IDC_CHK_DARK_EMP_MODE           1156
#define IDC_ST_PASSWORD2                1156
#define IDC_BTN_OK                      1157
#define IDC_BTN_CANCEL                  1158
#define IDC_GRID_CTRL_CAMERA_PARAM      1159
#define IDC_GRID_RECIPE_TABLE           1160
#define IDC_ED_RECIPE_NO                1162
#define IDC_BTN_REGIST                  1163
#define IDC_BTN_DELETE                  1164
#define IDC_BTN_RECIPE_SELECT           1165
#define IDC_EDIT_RECIPE_NAME            1166
#define IDC_BTN_LOAD                    1167
#define IDC_LIST_LOG                    1168
#define IDC_BTN_PROGRAMINFO             1168
#define IDC_EDIT_RECIPE_MEMO            1169
#define IDC_LIST_CHECK_DEBUG            1172
#define IDC_ST_MESSAGE                  1173
#define IDC_PROGRESS_TIMEER             1174
#define IDC_CHK_DEBUG_SIGOUT            1175
#define IDC_CHK_DEBUG_SIGIN             1176
#define IDC_CHK_DEBUG_SIGIN_RUN         1177
#define IDC_CHK_DEBUG_SIGOUT_ALIVEPULSE 1178
#define IDC_ST_DEBUG_SETTING            1179
#define IDC_CHK_SAVE_DEF_IN_TAB         1180
#define IDC_ED_SAVE_DEF_SIZE            1181
#define IDC_CHK_FIRST_TAB_DONOT_PROC    1182
#define IDC_CHK_ENABLE_NG_STOP          1183
#define IDC_STATIC_GROOVE_HEIGHT        1185
#define IDC_ED_NEGA_TAB_COAT_HEIGHT     1186
#define IDC_ED_NEGA_TAB_COAT_HEIGHT_PIX 1187
#define IDC_ED_V_GROOVE_HEIGHT          1188
#define IDC_ED_V_GROOVE_HEIGHT_PIX      1189
#define IDC_THUMBCTRL                   1190
#define IDC_BTN_REFRESH                 1192
#define IDC_CHK_MARKING_ALL             1193
#define IDC_ST_SERCH                    1193
#define IDC_ED_IGNORE_DISTANCE          1194
#define IDC_RD_LOTID                    1194
#define IDC_ED_IGNORE_SIZE              1195
#define IDC_RD_TIME                     1195
#define IDC_STATIC_PATH                 1196
#define IDC_DATETIMEPICKER_START        1196
#define IDC_ED_THRES_SPETTER            1197
#define IDC_DATETIMEPICKER_END          1197
#define IDC_ST_GROUP_SPETTER            1198
#define IDC_BTN_SEARCH                  1198
#define IDC_ED_SPT_MASK                 1199
#define IDC_BTN_EXPORT                  1199
#define IDC_CHK_DISABLE_SPTTER          1200
#define IDC_ST_TILDE                    1200
#define IDC_ED_SURFACE_NG_SIZE          1201
#define IDC_ST_IMAGE                    1201
#define IDC_ED_SURFACE_NG_SIZE_BTM      1202
#define IDC_PROGRESS_ECEXL              1203
#define IDC_CHK_DISABLE_PET             1203
#define IDC_BTN_OPEN_NG_IMG             1204
#define IDC_BTN_OPEN_OK_IMG             1205
#define IDC_BTN_ATTACH_IMG              1206
#define IDC_ED_SURFACE_MINSIZE          1207
#define IDC_CROP_THUMBNAIL              1208
#define IDC_BTN_LOT_END                 1209
#define IDC_LIST_MSG                    1211
#define IDC_ST_DELETE_PERIOD            1212
#define IDC_ST_DISK_SPACE_ALARM         1213
#define IDC_ED_FOIL_OUT_NG_X_SIZE       1213
#define IDC_ED_FOIL_BOTH_NG_X_SIZE      1214
#define IDC_ST_DISK_SPACE_ALARM_OFF     1214
#define IDC_ST_TAB_IMAGE                1215
#define IDC_BTN_SYSTEM_SET              1216
#define IDC_GROUP_CATHODE               1217
#define IDC_GROUP_ANODE                 1218
#define IDC_ST_TOP_COAT_HEIGHT          1219
#define IDC_ST_BTM_COAT_HEIGHT          1220
#define IDC_ST_TAB_COAT_HEIGHT          1221
#define IDC_ST_A                        1222
#define IDC_ST_COAT_HEIGHT              1222
#define IDC_ST_GROUP_SIGNAL_IN          1223
#define IDC_ED_FOIL_OUT_NG_X_SIZE_BTM   1223
#define IDC_ST_GROUP_SIGNAL_OUT         1224
#define IDC_ED_FOIL_BOTH_NG_X_SIZE_BTM  1224
#define IDC_ST_ALIVE_PULSE_IN           1225
#define IDC_ST_ALIVE_PULSE_OUT          1226
#define IDC_ST_READY_IN                 1227
#define IDC_ST_READY_OUT                1228
#define IDC_ST_RUN_IN                   1229
#define IDC_ST_CNT_RESET_ACK            1230
#define IDC_ST_ALIVE_PULSE_IN_OFF       1231
#define IDC_ST_READY_IN_OFF             1232
#define IDC_ST_RECIPE_CHANGE_IN         1233
#define IDC_ST_RAD_RECIPE_CHANGE_ACK    1234
#define IDC_ST_LOT_START_IN             1235
#define IDC_ST_LOT_START_ACK            1236
#define IDC_ST_RCP_NAME                 1237
#define IDC_ST_RUN_IN_OFF               1237
#define IDC_ST_RECIPE_CHANGE_IN_OFF     1238
#define IDC_ST_LOT_START_IN_OFF         1239
#define IDC_ST_CNT_RESET_IN             1240
#define IDC_ST_INK_MARK_IN              1241
#define IDC_ST_LOT_END_IN               1242
#define IDC_ST_CNT_RESET_IN_OFF         1243
#define IDC_ST_DISK_SPACE_ERROR         1244
#define IDC_ST_LOT_END_ACK              1245
#define IDC_ST_INK_MARK_IN_OFF          1246
#define IDC_ST_LOT_END_IN_OFF           1247
#define IDC_ST_ALIVE_PULSE_OUT_OFF      1248
#define IDC_ST_READY_OUT_OFF            1249
#define IDC_ST_CNT_RESET_ACK_OFF        1250
#define IDC_ST_DISK_SPACE_ERROR_OFF     1251
#define IDC_ST_RAD_RECIPE_CHANGE_ACK_OFF 1252
#define IDC_ST_LOT_START_ACK_OFF        1253
#define IDC_ST_LOT_END_ACK_OFF          1254
#define IDC_BTN_DATA_LOAD               1255
#define IDC_ED_CONTINUOUS_ALARM         1258
#define IDC_ED_SECTOR_COUNT             1259
#define IDC_ED_ALARM_COUNT              1260
#define IDC_GRID_WORD_IN                1260
#define IDC_GRID_WORD_OUT               1261
#define IDC_ST_INSP_INFO                1261
#define IDC_ST_RECIPE                   1262
#define IDC_GRID_BIT_IN                 1262
#define IDC_ST_INSP_COUNT               1263
#define IDC_GRID_BIT_OUT                1263
#define IDC_ST_TOTAL_COUNT              1264
#define IDC_ST_OK_COUNT                 1265
#define IDC_ST_NG_COUNT                 1266
#define IDC_ST_YIELD                    1267
#define IDC_ST_MACHINE_TYPE             1269
#define IDC_ST_CAM_PARAM                1270
#define IDC_ST_BASE_SETTING             1271
#define IDC_ST_RESOLUTION_Y             1272
#define IDC_ST_LANG_SETTING             1273
#define IDC_ST_RESOLUTION_Y2            1274
#define IDC_ST_OTHER_SETTING            1276
#define IDC_ST_JPEG_QUALITY             1277
#define IDC_ST_GROUP_RCP_SET            1278
#define IDC_ST_OVERFLOW                 1278
#define IDC_ST_GROUP_TAB_INFO           1279
#define IDC_ST_MISS_TAB_ID_MAX          1279
#define IDC_ST_INPUT_MM                 1280
#define IDC_ST_INPUT_PIX                1281
#define IDC_ST_TAB_WIDTH                1282
#define IDC_ST_TAB_PITCH                1283
#define IDC_ST_ROUND_RADIUS             1284
#define IDC_ST_RECIPE_NO                1285
#define IDC_BTN_CLEAR                   1286
#define IDC_ST_EDGE_DETECT_COND         1287
#define IDC_ST_COAT_BRIGHT              1288
#define IDC_ST_ROLL_BRIGHT              1289
#define IDC_ST_LIGHT_SETTING            1290
#define IDC_ST_MARKING_SETTING          1291
#define IDC_ST_DETECT_INFO              1292
#define IDC_ST_THRES_ORG                1293
#define IDC_ST_THRES_LOWER              1294
#define IDC_ST_DET_MIN_SIZE             1295
#define IDC_ST_INSP_WIDTH               1296
#define IDC_ST_MASK_OFFSET              1297
#define IDC_ST_THRES_SURFACE            1298
#define IDC_ST_MASK_SURFACE             1299
#define IDC_ST_MIN_SIZE_SURFACE         1300
#define IDC_ST_MAGNIFICATION            1301
#define IDC_ST_FOIL_IN_NG_SIZE          1302
#define IDC_ST_FOIL_OUT_NG_SIZE         1303
#define IDC_ST_FOIL_BOTH_NG_SIZE        1304
#define IDC_ST_SURFACE_NG_SIZE          1305
#define IDC_ST_NG_ALARM_SETTING         1306
#define IDC_ST_CONTINUE_ALRAM           1307
#define IDC_ST_SECTION_ALARM            1308
#define IDC_ST_FOIL_DEF_REMOVE          1309
#define IDC_ST_FOIL_DEF_REMOVE_DISTANCE 1310
#define IDC_ST_FOIL_DEF_REMOVE_SIZE     1311
#define IDC_ST_HORIZON                  1312
#define IDC_ST_JUDGE_TOP                1312
#define IDC_ST_GROUP_JUDGE              1313
#define IDC_ST_MAP_DISP                 1314
#define IDC_ST_JUDGE_TOP2               1314
#define IDC_ED_FOILEXP_GRAY_SIZE        1315
#define IDC_ED_SURFACE_GRAY_SIZE        1316
#define IDC_ST_GRAY_SIZE                1317
#define IDC_GRAPH_TACT_TIME             1318
#define IDC_ST_GROUP_PET_CHECK          1318
#define IDC_BTN_TACT_TIME               1319
#define IDC_ST_PET_MATRIX               1319
#define IDC_ST_PET_THRESHOLD            1320
#define IDC_ST_DISP_IMAGE               1321
#define IDC_ST_PET_CHECK_CNT            1321
#define IDC_CROP_THUMB                  1322
#define IDC_ST_SELECT_IMG               1323
#define IDC_ST_ORG_IMAGE                1324
#define IDC_GRID_DEFECT_INFO            1325
#define IDC_ED_TAB_MIN_BRIGHT           1327
#define IDC_RAD_DARK_ROLL               1328
#define IDC_RAD_LOGO1                   1329
#define IDC_RAD_LOGO2                   1330
#define IDC_RAD_LOGO3                   1331
#define IDC_RAD_PLC_MODE1               1332
#define IDC_RAD_PLC_MODE2               1333
#define IDC_ST_IP                       1334
#define IDC_ST_PORT                     1335
#define IDC_COM_IMAGEOUTFORMAT          1336
#define IDC_STATIC_IMAGESAVEINTERVAL    1337
#define IDC_BUT_LOGCLEAR                1341
#define IDC_CHECK_MOVELASTLOG           1343
#define IDC_BUT_CLIPBOARDCOPY           1344
#define IDC_CHECK_LOGSELECT             1345
#define IDC_CHECK_MOVELASTLOG2          1346
#define IDC_CHECK_TextPrint             1346
#define IDS_VIEW_RESULT                 32773
#define ID_INSP_INFO_VIEW               32775
#define ID_TREND_VIEW                   32777
#define ID_DEBUG                        32778
#define ID_Menu                         32779
#define ID_CAMERA_SETTING               32781
#define ID_CAMERA_VIEW                  32782
#define ID_CAMERA_WAVE                  32784
#define nCopyWidth                      32785
#define ID_DEBUG_START                  32787
#define ID_RECIPE_RELOAD                32788
#define ID_RECIPE_SETTING               32789
#define ID_SYSTEM_SETTING               32791
#define ID_BACKUP_DELETE_SETTING        32793
#define IDS_CROP_IMAGE_VIEW             32794
#define IDS_HISTORY_LOT_VIEW            32795
#define IDS_CROP_VIEW                   32796
#define IDD_DEBUG_CONTROL               32798

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        420
#define _APS_NEXT_COMMAND_VALUE         32799
#define _APS_NEXT_CONTROL_VALUE         1343
#define _APS_NEXT_SYMED_VALUE           316
#endif
#endif
